[package]
name = "libfs"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { version = "1.5.0", default-features = false, optional = true }
bento = {path = "../bento/rust" }

[features]
bitmap_u64 = ["byteorder"]
bitmap_be = []
